privacysandbox/privacy-sandbox-demos

services/home/docusaurus.config.js

Update algolia doc search apikey
Detailed mail from algolia was forwarded to @Seburan

[home] update algolia doc search apikey

---

docs/deploy-to-gcp.md
docs/deploy-to-linux-docker.md
services/home/docs/demos/single-touch-conversion-attribution.md

- [docs] fix deployment instructions
- run fmt

Fix documentation

---

services/dsp/package-lock.json
services/dsp/package.json

update dsp dependencies

---

services/news/package-lock.json
services/news/package.json

update news dependencies

---

services/travel/package-lock.json
services/travel/package.json

update travel dependencies

---

services/ssp/package-lock.json
services/ssp/package.json

update ssp dependencies

---

services/dsp/Dockerfile
services/news/Dockerfile
services/ssp/Dockerfile
services/travel/Dockerfile

closes #25 #21 #13 #12 #11
shop should be covered in other PR later.

[docker] update node version from 18 to 20

---

services/dsp/src/public/dsp-tag.js
services/dsp/src/public/js/join-ad-interest-group.js
services/ssp/src/index.js
services/ssp/src/public/js/run-ad-auction.js

add feature detection for fledge api for avoid error on browser not supported.

[api] feature detection

---

.gcloudignore
cloudbuild.yaml
docs/deploy-to-gcp.md
scripts/cicd_setup.sh
scripts/cloudrun_deploy.sh
services/home/.gcloudignore

migration from container registry to artifact registry 
- update deployment instructions : create artifact registry repo 
- update deployment script to deploy with config file
- added .gcloudignore to remove unnecessary files and folder from Cloud Build upload
- Fixes : time to build with Cloud Build was slow
Other: CI/CD

[cicd] migrate to artifact registry

---

services/topics/src/index.ts
services/topics/src/views/index.ejs

Update topics service - add TOPICS_SERVER_HOST via param
This way it can work in any environment
- Fixes #xxx
- [ x] Topics
Other:

Update topics service - add TOPICS_SERVER_HOST via param

---

.gcloudignore
cicd/cloudbuild.yaml
services/home/Dockerfile

home html files need to be built to be deployed by ci/cd. add docusaurus build operation in ci/cd
Other:
- CI/CD

[CI/CD] build html files with Cloud Build

---

services/shop/app/items/[id]/SubmitForm.tsx

- #114 has ts error
- only has workaround
- https://github.com/microsoft/TypeScript/issues/30584
- #114 
Other:

[shop] fix ts error

---

cicd/cloudbuild.yaml

the latest version of nodejs causes the build (on Cloud Build) to fail. forcing node image to "lts" version until it s fixed
https://github.com/facebook/docusaurus/issues/9286
- Fixes #xxx
Other:
CI/CD

[cicd] fix node version for build pipeline

---

services/dsp/src/index.ts
services/dsp/src/public/js/dsp.js
services/dsp/src/public/js/private-aggregation-worklet.js
services/dsp/src/public/js/private-aggregation.js
services/dsp/src/views/private-aggregation.ejs
services/news/src/index.ts
services/news/src/views/index.ejs

Please describe a summary of the changes.
- Fixes #xxx
Other:

Add Private Aggregation Reporting for News Site

---

services/home/docs/demos/index.md
services/home/docs/demos/vast-video-protected-audience.md
services/home/docs/intro.md

Misc fixes to the VAST API addition to the PS Demos site. 
N/A

VAST API fixes to docs.

---

services/home/docs/demos/index.md
services/home/docs/demos/vast-video-protected-audience.md
services/home/docs/intro.md

Please describe a summary of the changes.
On vast video use case doc : fix permalinks to GitHub commits (instead of branches)
Other:

[home] fix vast video doc

---

services/home/docs/demos/vast-video-protected-audience.md

Fixes to VAST Video API documentation links from relative to github permalinks where needed.
N/A
Other:

[home] Vast video fix

---

README.md
docs/deploy-to-gcp.md
docs/deploy-to-linux-docker.md

Update readme and deployment docs :
- remove origin trials tokens
- add cloud artifact registry and cloud build setup
NA
Other: Github docs

[github] update readme and deployment guide

---

docs/deploy-to-gcp.md
services/home/docs/demos/vast-video-protected-audience.md

fix urls pointing to dev environment
Other:

[home] fix docs links to dev environments

---

tools/postman_configurations/Privacy Sandbox.postman_collection.json

To update 'Privacy Sandbox.postman_collection.json' to have language format of JSON for the report body.
Other:

update 'Privacy Sandbox.postman_collection.json' to have a JSON language

---

tools/postman_configurations/Privacy Sandbox.postman_collection.json

Updated file "Privacy Sandbox.postman_collection.json" with missing comma in line 10 of the json body in createJob request.
Added field "report_error_threshold_percentage" in the createJob json body.
Other:

Postman configuration

---

.pre-commit-config.yaml
CHANGELOG.md

- [[cicd] upgrade pre-commit-config](https://github.com/privacysandbox/privacy-sandbox-demos/commit/f5e86b3068a36fb5fa8e0d01325134a97cfb8b4b)
- [[repo] update release notes](https://github.com/privacysandbox/privacy-sandbox-demos/commit/c8f47565b557471dfa24b26f7936b83820ab9318)
- 
- NA
Other:
- Tools
- CI/CD

Upgrade pre-commit and changelog

---

services/dsp-a/src/index.ts
services/dsp-b/src/index.ts
services/ssp-a/src/index.js
services/ssp-b/src/index.js

This allows resource access to all origin. This is demo code with nothing to protect, and there are no operations that mutate the state in the server. For better engineering practices, we can implement a proper CORS protection mechanism at a later time. 
Other:

Handle CORS

---

.env
cicd/.env.dev
cicd/.env.prod

Change .env vars for Cloud dev environment : 
- firebase hosting sites have been changed from privacy-sandcastle-dev-dsp-a.web.app to privacy-sandcastle-dev-dsp-a1.web.app , and from privacy-sandcastle-dev-dsp-b.web.app to privacy-sandcastle-dev-dsp-b1.web.app 
- set env for prod
Other:
- platform network

Update dev network

---

README.md
docs/deploy-to-gcp.md
docs/deploy-to-linux-docker.md
services/home/docs/demos/index.md
services/home/docs/demos/instream-video-ad-paapi-multi-seller-auction.md
services/home/docs/intro.md

Update documentation for multi-seller auction
Add documentation placeholder for insteam video demo
NA
Other:
- docs

Update documentation for multi-seller auction & insteam video demo

---

services/home/docs/demos/instream-video-ad-paapi-multi-seller-auction.md
services/home/docs/intro.md

fix broken links in use case demos doc
- Fixes #xxx
Other:

[home] fix broken links in docs

---

services/home/docs/demos/instream-video-ad-paapi-multi-seller-auction.md
services/home/package-lock.json
services/home/package.json

- upgrade docusaurus to 3.1.1
- fix duplicated index for instream video doc
NA
Other:

[home] upgrade doc platform

---

services/home/docs/demos/instream-video-ad-multi-seller.md

This PR removes the enrollment date estimate

Update enrollment timeline for the new origins

---

cicd/cloudbuild.yaml
services/home/docs/demos/instream-video-ad-multi-seller.md

This PR removes the enrollment date

Remove enrollment date

---

services/collector/Dockerfile
services/collector/src/go.mod
services/collector/src/main.go
services/home/package-lock.json
services/home/package.json

- Upgrade dependencies on home service (docusaurus)
- Upgrade dependencies on collector service (go)
- Fixes could not run docker build on collector
Other:

Fix dependencies on home & collector

---

.pre-commit-config.yaml
scripts/cloudrun_deploy.sh
services/home/docs/demos/instream-video-ad-multi-seller.md
services/home/package-lock.json
services/home/package.json

Add disclaimer to the demo `Instream video ad in a Protected Audience sequential auction setup`
upgrade docusaurus package used for building documentation
NA
Other:
- upgrade pre-commit
- clean gcp deploy script

add disclaimer to insteam video demo + upgrade docusaurus

---

README.md
docs/dependencies.md

Created a new doc to track codebase dependencies in plain english that should enable developers to better prepare for the content of the codebase
- There are no related Github Issues
Other:

Add dependencies doc

---

cicd/.env.dev
firebase.json

- update path to public folder for shop site
- remove inexistent topics service
- Fixes firebase deploy errors
Other:
- firebase deploy

fix firebase deploy script

---

.github/workflows/scorecard.yml
.pre-commit-config.yaml

Repository maintenance only : 
- upgrade pre-commit config with newer version of markdown lint
- upgrade scorecard workflow actions version
NA
Other:
- repository config

Upgrade pre-commit config and Scorecard analysis workflow 

---

.env
.github/workflows/scorecard.yml
.pre-commit-config.yaml
cicd/.env.dev
cicd/.env.prod
cicd/cloudbuild.yaml
package.json
services/home/docusaurus.config.js
services/home/package-lock.json
services/home/package.json
services/home/src/css/cookienotificationbar.min.css
services/home/src/theme/Root.js

Update Home site configuration (docusaurus configuration) to : 
1. enable  Google Tag Manager plugin
2. add a cookie consent banner using `react-cookie-consent` using [swizzling](https://docusaurus.io/docs/swizzling).  Inspired by this document : https://medium.com/@fokke_79992/cookie-consent-and-docusaurus-932aaef27d61
3. Add CSS for cookie consent banner
4. Upgrade docusaurus to v3.7.0 and upgrade to React v19.0
NA
Other:

[READY] Home site - Cookie consent banner for Google Analytics

---

.firebaserc.template
cicd/.env.dev
cicd/.env.prod
cicd/attestations/privacy-sandbox-attestations.json.dsp-x.dev.json
cicd/attestations/privacy-sandbox-attestations.json.dsp-x.prod.json
cicd/attestations/privacy-sandbox-attestations.json.dsp-y.dev.json
cicd/attestations/privacy-sandbox-attestations.json.dsp-y.prod.json
cicd/attestations/privacy-sandbox-attestations.json.ssp-x.dev.json
cicd/attestations/privacy-sandbox-attestations.json.ssp-x.prod.json
cicd/attestations/privacy-sandbox-attestations.json.ssp-y.dev.json
cicd/attestations/privacy-sandbox-attestations.json.ssp-y.prod.json
cicd/cloudbuild.yaml
docker-compose.yml
firebase.json

[infra] adding missing configuration for dsp-x, dsp-y, ssp-x, ssp-y
- firebase hosting config
- environment variables for cloud dev and prod environment
- ci/cd config for Cloud Build
- attestation files
-  NA
Other:

[infra] adding missing elements for dsp-x, dsp-y, ssp-x, ssp-y

---

.github/workflows/scorecard.yml
.pre-commit-config.yaml
services/home/docs/demos/single-touch-conversion-attribution.md

fix home doc - markdown 
- Fixes #xxx
Other:

fix markdown error due to <> tag not enclosed in back quotes

---

services/ad-tech/src/public/js/ssp/usecase/bidding-and-auction/ssp-x/construct-component-auction.ts
services/home/docs/demos/bidding-and-auction.md

- Fixing buyer documentation for B&A 
Other:

changes to buyer section B&A

---

README.md

Dev to stage
