services/shop/app/items/[id]/DSPTag.tsx
services/shop/lib/fetcher.ts
services/shop/package-lock.json
services/shop/package.json
services/shop/yarn.lock

currently, the error below causes on production server.
```
input: 'https://undefined:undefined/dsp-tag.js'
code: 'ERR_INVALID_URL'
```
This seems that calling process.env on client side happens and got undefined.
use `server-only` should prevent this, by only running code on server side.
https://nextjs.org/docs/getting-started/react-essentials#the-server-only-package

[shop] fix server side code

---

.github/dependabot.yml

changed dependabot running frequency from weekly to monthly to limit # of notifications in your mailbox
too many email notifications due to dependabot PR
Other:
Github repository security

Update dependabot.yml to monthly check

---

cicd/cloudbuild.yaml
services/shop/package-lock.json
services/shop/package.json
services/shop/src/index.js
services/shop/src/index.ts

Express JS session management did not work with Firebase/CloudRun due to Firebase constraints. it requires to name the session cookies "__session")
Express JS session management now uses memorystore module, to store session data in memory.
Enable session affinity on Cloud Run in case multiple instances are running so users get their cart content (it's only for demo purpose, in real-life session data should be managed using a third party database like Redis)
- Fixes #xxx
- [ x] Shop
Other:

[Shop] fix sessions for cloudrun

---

package.json
services/dsp/src/index.ts
services/dsp/src/public/html/video-ad-creative.html
services/dsp/src/public/js/join-ad-interest-group.js
services/dsp/src/public/js/video-ad-creative.js
services/home/docs/demos/retargeting-remarketing.md
services/home/docs/demos/single-touch-conversion-attribution.md
services/news/src/index.ts
services/news/src/public/css/video-ad-style.css
services/news/src/public/js/video-ad-helper.js
services/news/tsconfig.json
services/shop/src/env.js
services/shop/src/index.js
services/shop/src/index.ts
services/shop/src/lib/items.js
services/shop/src/public/css/global.css
services/shop/src/public/js/cart.js
services/ssp/package-lock.json
services/ssp/package.json
services/ssp/src/index.js
services/ssp/src/public/js/run-video-ad-auction.js
services/ssp/src/public/js/video-ad-tag.js
services/ssp/src/views/ads.html.ejs

- Fix ads endpoint missing on SSP service (ad creative could not be displayed on publisher site)
- FIx [Registering attribution sources](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registering-attribution-sources) : "Attribution-Reporting-Eligible" is a [Dictionary Structured Header](https://httpwg.org/specs/rfc8941.html#dictionary) and thus needed to be decoded properly. https://wicg.github.io/attribution-reporting-api/#issue-8fc7b5a1
- Fix remarketing use case documentation
- Fix single touch conversion attribution use case documentation
- [ x] Home
Other:
- run fmt on project files
- fix npm run clean commad

Fix shop ads

---

services/dsp/src/public/.well-known/privacy-sandbox-attestations.json

Update enrollment attestation to v2 format for dsp service
References : 
- https://github.com/privacysandbox/attestation
- https://github.com/privacysandbox/attestation/blob/main/how-to-enroll.md#upload-your-attestation-file
- 
- NA
Other:

Update enrollment attestation to v2 format for dsp service

---

CHANGELOG.md
services/dsp/src/public/.well-known/privacy-sandbox-attestations.json

add changelog / release notes to help users of Demos to track updates
Other:
- Changelog.md

Add changelog / release notes

---

cicd/attestations/privacy-sandbox-attestations.json.dsp.dev
cicd/attestations/privacy-sandbox-attestations.json.dsp.prod
cicd/attestations/privacy-sandbox-attestations.json.ssp.dev
cicd/attestations/privacy-sandbox-attestations.json.ssp.prod
cicd/cloudbuild.yaml
services/dsp/src/public/.well-known/privacy-sandbox-attestations.json
services/ssp/src/public/.well-known/privacy-sandbox-attestations.json

- Add Enrollment and Attestation files for dev and prod environment deployment
- Update Cloud Build configuration so copy attestation files for the target environment (dev or prod)
Other:
- CI/CD

Add attestation files v2 for DSP & SSP services

---

CHANGELOG.md
docs/deploy-to-gcp.md
docs/deploy-to-linux-docker.md
services/dsp/src/index.ts
services/dsp/src/public/.well-known/privacy-sandbox-attestations.json
services/dsp/src/public/js/dsp.js
services/dsp/src/public/js/private-aggregation-worklet.js
services/dsp/src/public/js/private-aggregation.js
services/home/docusaurus.config.js
tools/aggregatable_report_converter/README.md
tools/postman_configurations/Privacy Sandbox.postman_collection.json
tools/postman_configurations/workspace.postman_globals.json

- update deployment doc with instructions related to enrollment and attestations (how to bypass for local testing)
- fun fmt on dsp codebase
- run fmt on tools/
Other:
- Documentation

update deployment docs & run fmt

---

services/collector/Dockerfile
tools/hadolint

Add the `hadolint` dockerfile linter. Add a version pin for an apk package.

Add Dockerfile linter

---

docker-compose.yml
services/ssp-b/src/index.js
services/ssp-b/src/views/index.html.ejs

- This change makes multi-seller-auction demo in order to run both on docker & cloud run : FQDN (privacy-sandbox-demos-xxx.dev) can be used to communicate between services on the docker network.  Please remove references to DSP_A_HOST_INTERNAL, DSP_B_HOST_INTERNAL, SSP_A_HOST_INTERNAL, SSP_B_HOST_INTERNAL and use DSP_A_HOST, DSP_B_HOST etc. instead.
- fixes missing references to SSP-B / DSP-B in SSP-B  index page
- Fixes #xxx
Other:
- docker network settings

fixes multi-seller-auction demo to run both on docker & cloud run

---

CHANGELOG.md

This PR adds the 1.3.0 changelog

Add 1.3.0 changelog

---

cicd/cloudbuild.yaml

[cicd] fix missing build step for ad-server attestations
- NA
Other:
- CI/CD

[cicd] fix missing build step for ad-server attestations

---

.github/workflows/scorecard.yml

update version of scorecard workflow - the previous version contained an unsupported version of Github action relying on node 16. https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
imported newer version of scorecard.yml from https://github.com/ossf/scorecard/blob/main/.github/workflows/scorecard-analysis.yml
Other:

[github] update version of scorecard workflow

---

cicd/attestations/privacy-sandbox-attestations.json.dsp-a.dev
cicd/attestations/privacy-sandbox-attestations.json.dsp-b.dev

[dsp] update enrollment & attestation files for dev deployment
On dev environment Gogole Cloud deployment uses the following domain names :
- privacy-sandcastle-dev-dsp-a1.web.app
- privacy-sandcastle-dev-dsp-b1.web.app
- Fixes Attestation errors for those 2 domains
Other:

[dsp] update enrollment & attestation files for dev deployment

---

services/ad-tech/src/public/js/dsp/default/auction-bidding-logic.js

This is related to a recently released feature for supporting deal IDs and seat IDs in Protected Audience. This feature hasn't completely rolled out yet, and so, the corresponding fields may not always be available. As such, more defensive coding is warranted.
This change fixes the ID selection helper function to handle the field being undefined in some invocations. More specifically, `selectableBuyerAndSellerReportingIds` can be undefined or empty inside `selectDealId()`.
Also remove single quotes from field names to reduce visual clutter in the code.

Fix bug in selecting reporting ID in default bidding logic.

---

services/ad-tech/package-lock.json
services/ad-tech/package.json
services/ad-tech/src/controllers/report-store.ts

Upgrade the in-memory `report-store` module to use `node-cache` instead of an array. With this change, we can set a TTL for items in the store such that they'll expire progressively. This is as opposed to the current implementation where the entire store is cleaned periodically regardless of when the items were created.
Other:

Use node-cache for report-store

---

package.json
services/ad-tech/src/public/js/dsp/default/auction-bidding-logic.js
services/ad-tech/src/public/js/ssp/default/auction-decision-logic.js
services/ad-tech/src/routes/dsp/buyer-contextual-bidder-router.ts

Clean buyer's `auction-bidding-logic` and seller's `auction-decision-logic` for Protected Audience to make the scripts more readable.
Changelog:
* Update the top-level `package.json` file to run all pre-commit hooks with the `fmt` command.
* Move all logic related to console logging from `generateBid()` and `reportWin()` in `auction-bidding-logic` and `scoreAd()` and `reportResult()` in `auction-decision-logic` to helper function: `logContextForDemo()`.
* Move the logic to check for campaign status in `trustedBiddingSignals` during `generateBid()` to helper function: `isCurrentCampaignActive()`.
* Move the logic to reject bids if creative is blocked by the publisher during `scoreAd()` to helper function: `getRejectScoreIfCreativeBlocked()`.
* Include buyer hostname and origin in …

Make Protected Audience bidding and decision logic scripts more readable

---

services/ad-tech/src/controllers/key-value-store.ts
services/ad-tech/src/lib/constants.ts
services/ad-tech/src/lib/interest-group-helper.ts
services/ad-tech/src/public/js/dsp/default/auction-bidding-logic.js
services/ad-tech/src/public/js/ssp/default/auction-decision-logic.js
services/ad-tech/src/public/js/ssp/default/top-level-auction-decision-logic.js
services/ad-tech/src/public/js/ssp/run-sequential-ad-auction.js
services/ad-tech/src/routes/dsp/bidding-signals-router.ts
services/ad-tech/src/routes/dsp/buyer-contextual-bidder-router.ts
services/ad-tech/src/routes/dsp/buyer-router.ts
services/news/src/views/components/aside.ejs
services/news/src/views/display-ad-with-deals-multi-seller.ejs
services/news/src/views/display-ad-with-deals-only.ejs
services/news/src/views/display-ad-with-deals-single-seller.ejs

Refine the initial deals use-case implementation to more closely resemble real-world usage.
* Move the remaining interest group assembly logic to `interest-group-helper`. _(Currently, only assembling of interest group ads is included in this module.)_
* Define generalized interfaces for `InterestGroup` and `InterestGroupAdSize` to mirror expectations of the Protected Audience API.
* Define a new interface, `TargetingContext` that allows us to pass around arbitrary context across various modules on the `ad-tech` server while ensuring type-safety. This context includes: 
* `advertiser`: Hostname of the advertiser
* `usecase`: Used as switch for demonstrative purposes
* `itemId`: Advertiser product item ID
* `isUpdateRequest`: Is the request for an interest group object with an intent to …

Refine the initial deals use-case implementation to more closely resemble real-world usage.

---

services/news/src/constants.ts
services/news/src/index.ts
services/news/src/views/uc-publisher-ads-req.ejs
services/ssp/src/index.js
services/ssp/src/public/js/uc-publisher-ads-req/ad-tag.js
services/ssp/src/public/js/uc-publisher-ads-req/decision-logic.js
services/ssp/src/public/js/uc-publisher-ads-req/run-ad-auction.js
services/ssp/src/views/uc-publisher-ads-req/ad-tag.html.ejs

In this demo, we assume a publisher would like to exclude ads with certain product types. We’ll demonstrate a publisher page calling an SSP to perform a PAAPI auction, supplying product tags to exclude which have been selected by the user (e.g. “redShoe”). The SSP will exclude ads by calling their backend K/V server with the ad urls, and receiving ad metadata as JSON (e.g. {“productTags”: [“redShoe”, “shortsShoe”]}) which will be matched to the product tag to exclude.
Since PR460, this also includes;
- Requested changes from Syna
- Changes to deal with dev commit merge
- Request from Severin to parameterize urls in auction config (now being generated server side, like existing retargetting / remarking UC).
- Small nits from Kevin Lee comments in the design doc (e.g. switching tags names …

UC6: Incorporating publisher ad quality requirements in Protected (2nd PR attempt)

---

.env
cicd/.env.dev
cicd/.env.prod
cicd/cloudbuild.yaml
docker-compose.yml
firebase.json
nginx/nginx.conf

This changes removes all references to topics-server. This service is not used and won't be used. We refactored the code so that ad-tech service will include functionalities to [Observe and Access Topics](https://developers.google.com/privacy-sandbox/private-advertising/topics/web/implement). In future use cases, SSP/DSP will observe topics and use these information in auction/bidding signals.
NA
Other:

remove unused topics-server to clean codebase

---

.github/workflows/github-repo-stats.yml

Following the instructions at https://github.com/jgehrcke/github-repo-stats/wiki/Tutorial to install GitHub repo stats.
Objective is to collect GitHub repo analytics/insights for > 14days
Note : this change will only be active once merged with the default branch (main)
-  NA
Other:
- GitHub repository governance

Add github-repo-stats workflow file

---

.demos
.env
.env.deploy.template
.gcloudignore
cicd/.env.dev
cicd/.env.prod
monitoring/puppeteer-nodejs/.gcloudignore
monitoring/puppeteer-nodejs/.gitignore
monitoring/puppeteer-nodejs/.puppeteerrc.cjs
monitoring/puppeteer-nodejs/README.md
monitoring/puppeteer-nodejs/index.js
monitoring/puppeteer-nodejs/lib/constants.js
monitoring/puppeteer-nodejs/monitor-uc-remarketing.js
monitoring/puppeteer-nodejs/monitor-uc-single-touch-conversion.js
monitoring/puppeteer-nodejs/monitor-uc-template.js
monitoring/puppeteer-nodejs/monitor-uc-vast-video-paapi.js
monitoring/puppeteer-nodejs/monitor-uc-video-multi-seller-seq-auction-paapi.js
monitoring/puppeteer-nodejs/package-lock.json
monitoring/puppeteer-nodejs/package.json
scripts/cloudrun_deploy.sh
scripts/monitoring_deploy.sh
scripts/monitoring_setup.sh
scripts/monitoring_uptime.sh
services/home/.gcloudignore

This PR contains the skeleton for Synthetic Monitoring (Automated testing) with Cloud Monitoring.
- monitoring/puppeteer-nodejs contains the Cloud Run Function code to be executed by the Synthetic Monitors. 
- package will contains shared libraries and helpers to run the test cases
- each use case demo has their own function entry point defined in index.js and each use demo has their code in a dedicated file monitor-uc-<short_name>
- scripts/monitoring_setup.sh setup prerequisites and enables API. execute once.
- scripts/monitoring_deploy.sh deploys monitoring/puppeteer-nodejs as Cloud Function. 1 function per use case demo (todo : ideally it should be build once and deploys x time but Cloud Run Function does not allow this (yet))
- scripts/monitoring_uptime.sh configures the uptime …

[DRAFT][Monitoring] Add monitoring skeleton to dev branch

---

.env
cicd/.env.dev
cicd/.env.prod
cicd/cloudbuild.yaml
services/home/docusaurus.config.js
services/home/package-lock.json
services/home/package.json

- upgrade the documentation site to docusaurus 3.6.3
- clean dependencies
- update docusaurus config : remove unused algolia
- update docusaurus config with Google Analytics mesurement ID
- Add measurement ID as an environment variable in dev/prod
- Update CI/CD to load environment variables HOME_HOST and HOME_MEASUREMENT_ID when building home
- Fixes https://undefined in documentation site metadata (HOME_HOST was undefined at build time)
Other:

Documentation site (home) upgrade & analytics

---

.pre-commit-config.yaml

We don't want pre-commit.ci to auto fix PRs because commit from pre-commit.ci would trigger the cla/google polcy.
- The previous config did not seem to work. applying the config suggested here : https://pre-commit.ci/
Other:
- GitHub Repository

[github repo] disable pre-commit.ci autofix_prs

---

services/ad-tech/src/routes/common/common-router.ts
services/ad-tech/src/views/ssp/run-ad-auction.ejs
services/home/docs/demos/retargeting-remarketing.md

Bugfix: run-ad-auction.js was renamed to run-simple-ad-auction.js
Other:

bugfix run-ad-auction was moved to run-simple-ad-auction.js

---

package.json

There was an error in the docker start command 
Other:

fixing the start command in package.json

---

services/news/src/index.ts

The Remarketing use case wasn't working because the demo was creating the IG owner was DSP_HOST but it wasn't including DSP_HOST in the auction. 
The second possible solution is to add DSP_HOST as a possible buyer for SSP_HOST in the BUYER_HOSTS_TO_INTEGRATE_BY_SELLER_HOST variable (https://github.com/sidneyzanetti/privacy-sandbox-demos/blob/dev/services/ad-tech/src/lib/constants.ts#L185) but I'm not sure if it could have any other side effect in other use cases.
Other:

Remarketing use case wasn't working in the new structure

---

CHANGELOG.md
scripts/firebase_deploy.sh
services/home/docs/intro.md

- Documentation index was missing one use case "Event-level reports for single touch attribution"
- Firebase deploy script was missing the project setting command
NA
Other:

hotfix for documentation index and deploy script

---

.pre-commit-config.yaml
services/home/docs/demos/bidding-and-auction.md

Introduced an additiona pre-commit hook that will try to build `services/home` when one of the markdown doc is modified (or docusaurus config is modified). Will prevent invalid markdown (MDX) to be merged causing CI/CD to fail in dev/stage environment.
Due to pre-commit.ci limitation, on github pre-commit won't run `npm-build-services-home`. Ensure that pre-commit is installed on your machine before commiting files.
additionally fix bidding&action syntax.
Other:
- pre-commit config

Fix definitively invalid services/home docs issue

---

services/home/Dockerfile
services/home/nginx.conf

Re-introducing the nginx template to allows environment variable substitution in nginx.conf
Other:

[home] Reintroduce nginx.conf.template
